version: '3'
services:
    minio:
        #image: minio/minio
        build:
            context: ./minio
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ${DATA_PATH}/mino/data:/export
            - ${DATA_PATH}/minio/config:/root/.minio
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        command: server --console-address :9001 /export
